
name: 'classicmodels_modeling'
version: '1.0.0'
config-version: 2

profile: 'classicmodels_modeling'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by 'dbt clean'
  - "target"
  - "dbt_packages"

models:
  classicmodels_modeling:
    # Config for models in models/star_schema/
    star_schema:
      +schema: star_schema
      +materialized: table
    
    # Config for models in models/obt/
    obt:
      +schema: obt
      +materialized: table
